version: '3.8'

services:
  postgres:
    container_name: webapi
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=webapi